### ISSUE TITLE
Improving template images in the Godot documentation

### ISSUE THREAD

**Issue by Calinou** [sesopenko/gatt#1]
> The autotile templates provided with the official godot documentation on [Autotiles](https://docs.godotengine.org/en/stable/tutorials/2d/using_tilemaps.html#autotiles) aren't easy to use because the guide lines have been baked into each tile, requiring lots of editing using a graphics program (such as gimp).

Do you have suggestions for improving the template images featured in the documentation? Consider opening a pull request on [godot-docs](https://github.com/godotengine/godot-docs) :slightly_smiling_face:

**Comment by sesopenko** [comment]
If my attention is still on this domain in a little while I'll jump in and submit a PR.  I have some ideas on how to improve it, especially making the 3/4 view templates in the docs easier to understand how to use.  I'd like to generate some better templates with some wall line art first, so that it's more apparent just by looking at the template what a given template is doing.

**Comment by sesopenko** [comment]
Closing this because it's not an issue for this repository.
